### ISSUE TITLE
Elevation profile: option to display 

### ISSUE THREAD

**Issue by astridx** [astridx/pkg_aggpxtrack#1]
Elevation profile: option to display under/above the map rather than on?
https://gis.stackexchange.com/questions/186131/placing-controls-outside-map-container-with-leaflet

**Comment by bubi-luka** [comment]
I have tested this option on 4.0.5 and it works great. I had to tweak CSS a bit to get the desired effect, but other than that it works great.

**Comment by astridx** [comment]
Thank you very much for the kind feedback. Regarding CSS: This mainly depends on the Joomla template and that's why I only set `display` to keep the structure including the map stable.

**Comment by astridx** [comment]
Added this option to version 4.0.5
