### ISSUE TITLE
Taalbestand Nederlands

### ISSUE THREAD

**Issue by Peter-59** [astridx/pkg_aggpxtrack#10]
Is er ook een Nederlands taalbestand??
Ik zou graag de weergaveopties die nu in het Engels worden vermeld in het Nederlands hebben.

**Comment by astridx** [comment]
I added nl-NL for the plugin here: https://github.com/astridx/pkg_aggpxtrack/releases/tag/v1.1.9 
It is translated via https://www.deepl.com/translator

If you would like to improve this, I would be pleased if you would do it for this plugin too: https://github.com/astridx/pkg_aggpxtrack/blob/master/src/plugins/fields/aggpxtrack/language/nl-NL/nl-NL.plg_fields_aggpxtrack.ini

That way, others will also benefit.

![nl](https://user-images.githubusercontent.com/9974686/114560365-ebb76d80-9c6c-11eb-87de-93c46fe09517.png)

**Comment by hvdmeer** [comment]
Hi @astridx , I just installed 1.1.9 but fail to see all Dutch texts. 
Do I have to activate them?

**Comment by astridx** [comment]
Oh dear, I keep having problems with language files.

I moved the language file for the plugin from the Joomla language folder ( `/administrator/language/nl-NL` )  to the plugin folder ( `/src/plugins/fields/aggpxtrack/language/nl-NL/` ). Perhaps this is the problem.

Can you please have a look, if you have language files ( `nl-NL.plg_fields_aggpxtrack.ini` and `nl-NL.plg_fields_aggpxtrack.sys.ini` ) for the plugin in both folders? If so please delete the one in  `/administrator/language/nl-NL/`

**Comment by astridx** [comment]
And please have a look into `/plugins/fields/aggpxtrack/aggpxtrack.xml`. It should look like this


```
<?xml version="1.0" encoding="utf-8" ?>
<extension type="plugin" version="3.8.0" group="fields" method="upgrade">
	<name>plg_fields_aggpxtrack</name>
	<author>Astrid Günther</author>
	<creationDate>2021-04-13</creationDate>
	<copyright>(C) 2021 Astrid Günther. All rights reserved.</copyright>
	<license>GNU General Public License version 2 or later; see LICENSE.txt</license>
	<authorEmail>info@astrid-guenther.de</authorEmail>
	<authorUrl>www.astrid-guenther.de</authorUrl>
	<version>1.1.9</version>
	<description>PLG_FIELDS_AGGPXTRACK_XML_DESCRIPTION</description>
	<files>
		<file>CHANGES.txt</file>
<file>aggpxtrack.xml</file>
<folder>layouts</folder>
<folder>language</folder>
<folder>tmpl</folder>
<folder>forms</folder>
<folder>field</folder>
<file plugin="aggpxtrack">aggpxtrack.php</file>
<folder>params</folder>
	</files>
	<!-- Media files -->
    <media folder="media/plg_fields_aggpxtrack" destination="plg_fields_aggpxtrack">
		<folder>d3</folder>
<folder>css</folder>
<folder>js</folder>
<folder>leaflet-gpx</folder>
<folder>leaflet</folder>
<folder>leaflet-panel-layers</folder>
<folder>leaflet-easyPrint</folder>
<folder>Leaflet.Elevation-master</folder>
<folder>leaflet-omnivore</folder>
<folder>Leaflet.fullscreen</folder>
<folder>fonts</folder>
<folder>L.Control.Locate</folder>
<folder>GoogleMutant</folder>
<folder>Leaflet.awesome-markers</folder>
	</media>

	<config>
		<fields name="params">
			<fieldset name="basic">
				<field
					name="directory"
					type="folderlist"
					label="PLG_FIELDS_AGGPXTRACK_PARAMS_DIRECTORY_LABEL"
					description="PLG_FIELDS_AGGPXTRACK_PARAMS_DIRECTORY_DESC"
					directory="images"
					hide_none="true"
					recursive="true"
				/>
				<field
					name="preview"
					type="hidden"
					label="PLG_FIELDS_AGGPXTRACK_PARAMS_kPREVIEW_LABEL"
					description="PLG_FIELDS_AGGPXTRACK_PARAMS_PREVIEW_DESC"
					class="btn-group"
					default="false"
					>
					<option value="false">JNO</option>
				</field>
				<field
					name="image_class"
					type="textarea"
					label="PLG_FIELDS_AGGPXTRACK_PARAMS_IMAGE_CLASS_LABEL"
					description="PLG_FIELDS_AGGPXTRACK_PARAMS_IMAGE_CLASS_DESC"
					size="40"
				/>
			</fieldset>
		</fields>
	</config>
</extension>

```

There should not be a separate <language>- tag. 
There shoul be `<folder>language</folder>` within `<files>`

**Comment by hvdmeer** [comment]
The XML seems to be identical and I have no language file in the administrator but I do in the plugin folder.

**Comment by astridx** [comment]
It looks like I am not allowed to see the page. Am I doing something wrong?

**Comment by hvdmeer** [comment]
My bad. I first set it as a test article on a Super User level and the put more info in it and forgot only I can see it. It is set for Public now. :)

**Comment by astridx** [comment]
Can you please have a look, if you have language files ( en_GB.plg_fields_aggpxtrack.ini and en.GB.plg_fields_aggpxtrack.sys.ini ) for the plugin in both English folders 
( /administrator/language/en_GB and /src/plugins/fields/aggpxtrack/language/en_GB/ ). If so please delete the one in /administrator/language/en_GB.

**Comment by hvdmeer** [comment]
In ' /administrator/language/en_GB' I have the files
en-GB.com_aggpxtrack.ini
en-GB.com_aggpxtrack.sys.ini

And in 'plugins/fields/aggpxtrack/language/en-GB' 
en-GB.plg_fields_aggpxtrack.ini
en-GB.plg_fields_aggpxtrack.sys.ini

**Comment by astridx** [comment]
> In `/administrator/language/en_GB` I have the files
> en-GB.com_aggpxtrack.ini
> en-GB.com_aggpxtrack.sys.ini
> 
> And in `plugins/fields/aggpxtrack/language/en-GB`
> en-GB.plg_fields_aggpxtrack.ini
> en-GB.plg_fields_aggpxtrack.sys.ini
> 
> I've renamed the two in the administrator folder but still only English

Thanks for the info. This is fine too.


There was typo in the Dutch language file. I fixed this here: https://github.com/astridx/pkg_aggpxtrack/releases/tag/v1.1.10
But that cannot be the reason why no string was displayed at all. 
That  is why I had a deeper look.

Please take a look at the following if you still have problems.

Aktivate language debug mode:

![gpx1](https://user-images.githubusercontent.com/9974686/114880576-754c7400-9e02-11eb-9b4f-b59d7c87601c.PNG)

Make sure, that nl is active for site **and** admin. Here in the picture I activated it for site:

![gpx2](https://user-images.githubusercontent.com/9974686/114880580-767da100-9e02-11eb-94bb-0b7bfa547f55.PNG)

You shoudl see `nl-NL` when you edit the custom field:

![gpx3](https://user-images.githubusercontent.com/9974686/114880582-767da100-9e02-11eb-8f12-61c84c09d6b7.PNG)

Youd shoudl see `nl-NL` in the frontend:

![gpx4](https://user-images.githubusercontent.com/9974686/114880585-77aece00-9e02-11eb-897e-5e5f6ae294c6.PNG)

In the lower section of the debug console you can check which language files are loaded. 

Please write me if the Dutch strings are not displayed as expected. 

![gpx5](https://user-images.githubusercontent.com/9974686/114880588-78476480-9e02-11eb-8bbd-696a7ba1c4ed.PNG)

I am also happy if you write me if everything is OK.

**Comment by hvdmeer** [comment]
With the language debug switched on everything is in Dutch, front- and backend, and I see the files loaded in the frontend.
When I switch the language debug off again, I get the English text.

I didn't mention it earlier but the field is partly Dutch and partly English. I guess it has to do with core translations and plugin translations?
![aggpx-debug](https://user-images.githubusercontent.com/7062995/114885826-57cdd900-9e07-11eb-8184-9c0e1f691459.png)

**Comment by astridx** [comment]
Now I have to ask again. You see everything correctly in Dutch when debugging is activated. If you switch off the debugging, it is not correct in Dutch but the Joomla Core texts in Dutch and the texts of my Custom Field in English. This is the case in the backend and in the frontend. Did I understand that correctly?

I have just tried this out myself. I always have debugging on. I have just deactivated it. But I still see Dutch.
Do you notice anything else in the debugging output? Is there an error displayed here?

**Comment by hvdmeer** [comment]
There are no real errors in the page but I do see these cookie errors:
![aggpx-errors](https://user-images.githubusercontent.com/7062995/115205216-9dd1b800-a0f9-11eb-8e89-de3cf38b9336.jpg)

**Comment by astridx** [comment]
@hvdmeer

It would be great if you could test this. 
 

https://github.com/astridx/pkg_aggpxtrack/releases/tag/v1.1.12

I put the language files back into the joomla admin folder. Maybe your joomla wants to have them there in any case.

**Comment by hvdmeer** [comment]
Thank you Astrid, somehow this works for me. Now all texts are in Dutch.
Could it be since my original site was built in J1.0 and upgraded/migrated over the years? 
Anyway, thank you for fixing it for me :)

I will bookmark the translation file to see if any edits in Dutch are possible.

**Comment by astridx** [comment]
Then the problem is solved, right? (I prefer it when I understand it correctly. Actually, as far as I know, the language files in the plugin directory, should overwrite those in the Joomla Administrator directory. But anyway. The main thing is it is solved.)
If you like to improve the texts, you can do it directly in Github here.

https://github.com/astridx/pkg_aggpxtrack/blob/master/src/administrator/language/nl-NL/nl-NL.plg_fields_aggpxtrack.ini

![pkg_aggpxtrack nl NL plg_fields_aggpxtrack ini at master · astridx pkg_aggpxtrack](https://user-images.githubusercontent.com/9974686/115460307-66adf480-a228-11eb-9109-b3799870c872.png)
