### ISSUE TITLE
Elevation (gain/max/loss) in round numbers?

### ISSUE THREAD

**Issue by hvdmeer** [astridx/pkg_aggpxtrack#11]
Hi Astrid, after a long time I want to make some progress with aggpxtracks. :)
I have now one GPX track from a run of mine in an article and wanted to show the elevation gained. And it is shown in very precise number:
> Elevation (gain): | 312.80 meter

Wouldn't it be better if it is shown in round numbers, in this case 312 meter.

**Comment by astridx** [comment]
You are right. I will change this in the next version.

**Comment by astridx** [comment]
See https://github.com/astridx/pkg_aggpxtrack/releases/tag/v1.1.10
