### ISSUE TITLE
problem viewing the top interactive height profile

### ISSUE THREAD

**Issue by Philippe-FRICH** [astridx/pkg_aggpxtrack#12]
Hello
Great job. 
I have a Whatever the setting of the top margin, the indications (circled in red) at the top are cut off. Is this a bad setting on my part. 
Thank you for your help.
(If you are interested, I will prepare the French translation for you.)
<img width="595" alt="capture 2021-04-18 à 11 16 25" src="https://user-images.githubusercontent.com/47430394/115140894-de69fc80-a039-11eb-843f-b04716481ddf.png">
<img width="456" alt="capture 2021-04-18 à 11 17 57" src="https://user-images.githubusercontent.com/47430394/115140917-f3df2680-a039-11eb-8069-f22a79d10a7e.png">

**Comment by astridx** [comment]
Thank you for using aggpxtrack and for the kind feedback. 
The margin values are not the cause that the text for the altitude not being displayed in the control. They only cause the map to have a larger distance to the borders of the map. 

The next picture shows how it should look. The text "1443" is cut in your case.

![1](https://user-images.githubusercontent.com/9974686/115157318-e604c200-a088-11eb-864e-b9b7ce837c0c.PNG)


If it is important to you that the height information is also displayed in the control, then the following CSS is helpful. 

```
.leafletmap svg {
    overflow: visible;
}
```

Do you know where to insert it? In Joomla templates there is usually a user.css for this.   For example, for the standard template Protostar like this: https://docs.joomla.org/J3.x:Adding_a_custom_CSS_with_Protostar

**Comment by Philippe-FRICH** [comment]
Thank you for your quick reply.
It's perfect with the given CSS.
Will the plugin work under joomla 4?
How should I give you the fr-FR.plg_fields_aggpxtrack.ini file
I just have to make some corrections.
Should we also do fr-FR.com_aggpxtrack.ini?

**Comment by astridx** [comment]
> Thank you for your quick reply.
> It's perfect with the given CSS.

Great

> Will the plugin work under joomla 4?

I have started a J4 version. Now I would like to wait for the RC version and then see again if everything works.



> How should I give you the fr-FR.plg_fields_aggpxtrack.ini file
> I just have to make some corrections.
> Should we also do fr-FR.com_aggpxtrack.ini?

I added untranslated files here:
https://github.com/astridx/pkg_aggpxtrack/releases/tag/v1.1.12

If you like you can use the files in this release.

Or you change the strings directly in this file: https://github.com/astridx/pkg_aggpxtrack/blob/master/src/administrator/language/fr-FR/fr-FR.plg_fields_aggpxtrack.ini

You are right. Currently only the plugin is used, so translation is only needed for these strings.

**Comment by Philippe-FRICH** [comment]
Hello
I used the second link to directly edit the fr-FR.plg_fields_aggpxtrack.ini file
Hope my handling is good.
Do not hesitate to call on me to try the version under joomla 4, I am looking forward.
Best regards

**Comment by astridx** [comment]
OK. If you like you can change directly in Github. You haven't changed anything yet, right? At least I don't see it.
![pkg_aggpxtrack fr FR plg_fields_aggpxtrack ini at master · astridx pkg_aggpxtrack](https://user-images.githubusercontent.com/9974686/115459636-93154100-a227-11eb-9b0d-7feede81c393.png)

**Comment by Philippe-FRICH** [comment]
weird, I had done ...
I just started over and put it as an attachment in case it didn't work
[fr-FR.plg_fields_aggpxtrack.ini.zip](https://github.com/astridx/pkg_aggpxtrack/files/6346877/fr-FR.plg_fields_aggpxtrack.ini.zip)
