### ISSUE TITLE
Are you planing to include this extension on JED (Joomla Extension Directory)?

### ISSUE THREAD

**Issue by bubi-luka** [astridx/pkg_aggpxtrack#15]
Hi! I am just wondering why you did not add this extension to the JED website so we, the users, could easily install it from Joomlas admin area?

**Comment by astridx** [comment]
Thank you for your advice. My extensions are small private projects. I'm happy if others find my extensions helpful and I'm also happy to adapt them to individual wishes.
 In the JED I think extensions written for the general public should be listed.

**Comment by bubi-luka** [comment]
I understand and respect that. It is just that your extension works and do the thing that was designed for very well. In fact better than most similar on the JED. :) Best wishes!
