### ISSUE TITLE
Aggpxtrack and Joomla 4.x

### ISSUE THREAD

**Issue by FrankReisenhofer** [astridx/pkg_aggpxtrack#16]
Dear developers,

Are you planing to support Joomla 4.x with your plugin?

Thanks for sharing some information.

Have a nice day,

**Comment by astridx** [comment]
In the releases there is already a version for joomla 4. It is not an update, but a new version. It was important to me to get rid of old things and rebuild. 

Is that sufficient? If an upgrade is desired, I will gladly support you.
