### ISSUE TITLE
Missing translation in Field form

### ISSUE THREAD

**Issue by hvdmeer** [astridx/pkg_aggpxtrack#2]
After installing aggpxtrack I added a field for it. 
At entering the information in this form I noticed a translation into English is missing for:
Höhe der Karte
Also the mouseover is in Deutsch.
![aggpxtrack01](https://user-images.githubusercontent.com/7062995/73933389-a36c2500-48dc-11ea-84b3-80d108ca30e4.png)

**Comment by astridx** [comment]
Thank you very much for your hint. I took it on my todo.

**Comment by astridx** [comment]
See 
https://github.com/astridx/pkg_aggpxtrack/pulls?q=is%3Apr+is%3Aclosed
and 
Release 1.1.4
https://github.com/astridx/pkg_aggpxtrack/releases/tag/v1.1.4
