### ISSUE TITLE
[Idea] Count download gpx-files

### ISSUE THREAD

**Issue by hvdmeer** [astridx/pkg_aggpxtrack#21]
Hi Astrid!

I used your plugin on a few routes I ran to test it and now was thinking in adding more runs 🙂 

As I watched an article with link I couldn't find any option to see if and how many times the GPX-file was downloaded. Is it possible to add this somewhere?

**Comment by astridx** [comment]
@hvdmeer Thank you for your suggestion. 
It is certainly possible to count the downloads. However, I would like to limit myself to the geographical functions. Maybe you would like to use a download component like https://www.phoca.cz/phocadownload for statistics?

**Comment by hvdmeer** [comment]
Totally forgot about my question and it sunk into the Github notifications. It's fine if you don't feel the need to add it. 
I was thinking about a download manager but it seems a little bit much code just for download numbers. I'm thinking how I want to do this
