### ISSUE TITLE
[4.0.3] GPX Filename wird im Backend nicht richtig selektiert

### ISSUE THREAD

**Issue by FrankReisenhofer** [astridx/pkg_aggpxtrack#22]
Hallo Astrid,

in den letzten Tagen habe ich meine Webseite von Joomla 3.10.5 auf 4.0.5 migriert und dabei auch dein Plugin auf die 4.x Version umgestellt.

Im Frontend schaut danach alles prima aus :-).

Im Backend habe ich jedoch eine Herausforderung.

Wenn ich im Backend bei einem Artikel das Feld von aggpxtrack öffne und versuche eine GPX Datei zu selektieren, so erscheint zunächst das folgende Fenster:

![image](https://user-images.githubusercontent.com/37330222/151378259-c8fff1f7-1357-426e-b647-4969013f2f35.png)

Naja: "Change Image" würde mich nicht so stören. Aber das hat wohl Auswirkungen.

Wenn ich ein GPX File im Dialog auswähle, so wird anschließend zum Beispiel folgender Inhalt angezeigt:

images/gpxtracks/ElHierro2011/GPS_ELHIERRO_2011.gpx#joomlaImage://local-images/gpxtracks/ElHierro2011/GPS_ELHIERRO_2011.gpx?width=0&height=0

Woher "#......." kommt, ist mir nicht klar.

Bin mir nun nicht sicher, ob ich hier eine falsche Einstellung im neuen Medienmanager habe, oder ob das an deinem Plugin liegen kann. 

Hast du eine Idee?

Danke für einen Tipp und noch einen schönen Tag wünscht dir

Frank
 
 P.S.: ..Ups: https://github.com/astridx/pkg_aggpxtrack/issues/19 hab ich gerade gesehen. Leider funktioniert dein Workaround nicht ganz. Ich kann im Feld selbst nichts eingeben. Das geht nur über den Select-Button :-(
 
 P.P.S: Hab als Workaround den Wert via SQL direkt in der Datenbank korrigiert

**Comment by astridx** [comment]
> Woher "#......." kommt, ist mir nicht klar.

Das wird von Joomla eingefügt, Das kommt daher, dass Aggpxtrack das Media Feld von Joomla erweitert. Bei Gelegenheit werde ich das anpassen. Du kannst das schon jetzt so speichern und musst nicht über die Datenbank gehen. Im Frontend wird es richtig weiterverarbeitete. Oder hast du im Frontend Probleme?

**Comment by FrankReisenhofer** [comment]
Danke für deine schnelle Rückmeldung.

"Du kannst das schon jetzt so speichern"...

Was meinst du damit? Muss ich da etwas in deinem Feld ändern oder beim Mediamanager?

Nach meiner Änderung in der Datenbank hat alles im Frontend prima geklappt

**Comment by astridx** [comment]
> Was meinst du damit? Muss ich da etwas in deinem Feld ändern oder beim Mediamanager?

Wenn ich dich richtig verstehe nirgendwo. Oder kannst du das GPX gar nicht auswählen?

**Comment by FrankReisenhofer** [comment]
Also: Wenn ich über den Button "Auswählen" ein gpx File selektiere, 

dann werden in das Feld Zeichenketten der Form 

images/gpxtracks/ElHierro2011/GPS_ELHIERRO_2011.gpx#joomlaImage://local-images/gpxtracks/ElHierro2011/GPS_ELHIERRO_2011.gpx?width=0&height=0

Nun hab ich aus meiner Sicht zwei Möglichkeiten:

1) Ich ändere den Wert in der Datenbank via SQL so ab, dass die Zeichenkette ab # gelöscht wird
-> Alles im Frontend okay
2) Den Wert im Feld lasse ich unverändert (also mit # ) 
-> Im Frontend wird eine leere Karte angezeigt. 

Daher sehe ich im Moment nur die Möglichkeit, das Verhalten via SQl zu korrigieren, da das Feild selbst nicht editierbar ist. Aber vielleicht liegt das ja an meine Joomla-Einstellungen.

Der Workaround mit dem SQL ist für mich aber im Moment auch okay. Alles gut! Einen guten Start in die neue Woche wünscht dir Frank

**Comment by astridx** [comment]
Wird bei dir in 2 tatsächlich eine weiße Seite angezeigt?

**Comment by FrankReisenhofer** [comment]
https://www.reisenhofer.de/index.php/de/

Hab dort für Testzwecke eine Karte eingebaut

**Comment by astridx** [comment]
Die Fehlermeldung lautet:
`Uncaught TypeError: L.GPX is not a constructor`

![reis](https://user-images.githubusercontent.com/9974686/151831467-ea579345-844a-4861-87d1-71d9dc9e33fb.PNG)

Das deutet darauf hin, dass das JavaScript für das GPX nicht korrekt geladen wird. Ich kann auch den Eintrag zu der Datei bei dir nicht finden. Bei dir sieht das so aus:

![reis2](https://user-images.githubusercontent.com/9974686/151831540-da54f1fb-830c-45d6-afa3-d0a867fd39ab.PNG)

Ich glaube der JCH optimiert bei dir. Das ist keine Erklärung dafür, dass es korrekt läuft, wenn du den Namen in der Datenbank änderst. 

Es ist allerdings so, dass ich den Namen nicht ändern muss, GPXTrack erkennt die GPX. Und es gibt andere Joomla 4 Installationen ohne Probleme. Ich kann  das Problem nicht nachstellen.

Könntest du es einmal mit deaktiviertem JCH testen oder für die GPX Datei eine Ausnahme anlegen?

**Comment by FrankReisenhofer** [comment]
Danke für deine Analyse.

Hab JCH deaktiviert. Mit gleichem Ergebnis.

Ein Beispiel, wo eine richtige Karte angezeigt wird, ist hier: https://www.reisenhofer.de/index.php/de/fotos-de?view=article&id=330:hier-waren-wir-unterwegs-14&catid=37:badkohlgrub2021

**Comment by astridx** [comment]
Hast du auch alle Caches gelöscht?

**Comment by FrankReisenhofer** [comment]
Hab ich. Auch den Browser-Cache.

Hab gerade wegen andere Plugins nach der 4.x Migration noch so manche Herausforderungen.

Daher habe ich die Karte auf der Startseite wieder entfernt. Dachte, dass könnte dir bei der Analyse helfen.

Schaut aber so aus, als wäre das nur bei mir so. Ich hab aber aktuell einen Workaround mit dem SQL :-).

Vermute mal, dass du dein Plugin in absehbarer Zeit dahingehend anpassen wirst, dass keine #.... Zeichen mehr im UI erscheinen. Dann teste ich das gerne wieder.

**Comment by astridx** [comment]
Ich hoffe es ist OK für dich, dass ich dein Issue wieder öffne. Es ist der Erinnerer für mich, dass ich  beim Speichern den Text nach der Raute entferne.

**Comment by FrankReisenhofer** [comment]
Passt. Alles gut :-)

**Comment by astridx** [comment]
Als Erinnerer: Gibt es einen Zusammenhang hiermit: https://forum.joomla.de/thread/15336-offline-bild-seltsame-pfadangabe-in-der-konfiguration/?postID=102105&highlight=seltsame%2BPfad#post102105 ?

**Comment by astridx** [comment]
Yep: https://github.com/joomla/joomla-cms/pull/37008

**Comment by astridx** [comment]
@FrankReisenhofer
Ich habe gerade in einer frischen Joomla 4.1 ein paar Tracks eingegeben. Ich hatte wieder keine Probleme. 

Da gab es auch eine Änderung im https://github.com/joomla/joomla-cms/pull/37008 . Ich bin mir nicht sicher ob diese dein Problem behebt,

Wenn du die GPX-Datei auswählst, wird immer noch eine Raute und weiterer Text an den Namen der Datei angehangen:

`images/com_aggpxtrack/collonchevres.gpx#joomlaImage://local-images/com_aggpxtrack/collonchevres.gpx?width=0&height=0`

 Im Frontend wird dies aber getrennt und richtig weiter bearbeitet. 

 Hast du das Aggpxtrack Feld schon einmal mit Joomla 4.1 getestet? Hattest du da auch noch Probleme und musstest den Wert in der Datenbank ändern?

**Comment by FrankReisenhofer** [comment]
@astridx 

So oft habe ich keine neuen GPX Tracks. Daher habe ich das bisher auch mit Joomla 4.1 nicht getestet.

Hab auf meiner Titelseite gerade wieder eine Karte eingebaut:

www.reisenhofer.de

Leider wird wieder eine leere Karte angezeigt.

Denke, wir sollten auf den Bugfix in Joomla-Core warten :-) (https://github.com/joomla/joomla-cms/pull/37008 .

**Comment by astridx** [comment]
Du hast recht. Ich hatte das falsch gesehen. https://github.com/joomla/joomla-cms/pull/37008 wurde eine Woche nach dem Release von 4.1 gemerged. Bei meinem Kommentar ging ich fälschlicherweise davon aus, dass er in 4.1 integriert ist.

**Comment by FrankReisenhofer** [comment]
@astridx : Hab das gerade mit Joomla 4.1.1 probiert.

Leider hat sich nichts verändert:

![image](https://user-images.githubusercontent.com/37330222/161971690-6653731d-271f-4a80-a3a2-8c351664f350.png)

**Comment by astridx** [comment]
Ich habe gerade eine neue Version (4.0.4) erstellt. Du solltest sie im Backend sehen können.

Bei der Auswahl lasse ich den Anhang `#joomlaImage....,` der von Joomla automatisch hinzugefügt wird, wenn man die Funktionen des Joomla-Medienmanagers benutzt. Im Layout, das für die Anzeige im Frontend zuständig ist, lösche ich es nun aber. Ich denke, damit sollte das Problem auch bei dir gelöst sein.

Ich würde mich freuen, wenn du es einmal testen würdest.

**Comment by FrankReisenhofer** [comment]
Hallo @astridx ,

prima, dass du das jetzt so eingebaut hast.

Hab das gerade mit deiner neuen Plugin-Version 4.0.5 getestet:

Alles gut :-). 

Danke für deine Hilfe
