### ISSUE TITLE
Error on opening custom field properties on J4

### ISSUE THREAD

**Issue by bubi-luka** [astridx/pkg_aggpxtrack#23]
Hi!

I am getting the following error on latest Joomla instalation 4.1.0, with extension version 4.0.3:
```
An error has occurred.
  0 Joomla\Filesystem\Folder::files: Path is not a folder. Path: /var/www/joomla4page/images/com_aggpxtrack
```
The extension works normally.
Regards; Luka

**Comment by bubi-luka** [comment]
I am also getting the following error on saving the extensions global settings:
`An error has occurred.

    500 behavior::tabstate not found. `

**Comment by astridx** [comment]
Thanks for informiert me.

Which aggpxtrack version do you have installed? Did you update from joomla3 to joomla 4? Did you uninstall the aggpxtrack version for joomla 3 beforehand?

**Comment by bubi-luka** [comment]
Hi!

I have upgraded from Joomla3 to Joomla4 using Joomla upgrade mechanism. I think I just updated aggpxtrack from joomla3 version to joomla4, without uninstalling the previous version. 

---

| Extension | Version |
| :--- | :--- |
Aggpxtrack | 4.0.3 |
Aggpxtrack Extension Package | 4.0.3 |
Fields - Aggpxtrack | 4.0.3 |
Installer - Aggpxtrack | 3.0.2 |

**Comment by astridx** [comment]
I think this is the problem. You need to uninstall the aggpxtrack version.
Please read this: https://github.com/astridx/pkg_aggpxtrack#pkg_gpxtrack

**Comment by bubi-luka** [comment]
Thank you! That fixed the first issue. On uninstalling the 4.0.3 version and reinstalling it there are no more errors on extensions settings page.

I am still getting an error on global settings, when I click Save and Close

> `500 behavior::tabstate not found. `

I believe in Joomla4 after you close the global settings page, Joomla will redirect you to the page that is in connection with the settings that you were on, when you clicked Save and Close. The settings get saved normally and the button Save does not show the mentioned error.

**Comment by astridx** [comment]
I just installed aggpxtrack from scratch under Joomla 4.1 and the error was not shown to me. I also can't imagine how aggpxtrack generates the error. 

Do you user helix? In this case please see: https://stackoverflow.com/questions/65854685/error-500-behaviortabstate-not-found-when-trying-to-access-sp-page-builder

**Comment by astridx** [comment]
I was just about to reporduce your issue, but couldn't. can you please tell me more specifically where you were redirected to when you saw the error?

**Comment by bubi-luka** [comment]
The workflow to generate this error is the following:
System -> Global Configuration -> (Components) Aggpxtrack -> Close (or Save and Close)

Name | Version
-- | -- 
Aggpxtrack |  4.0.3
Aggpxtrack Extension Package |  4.0.3
Fields - Aggpxtrack |  4.0.3

Setting | Value
-- | --
PHP Built On  | Linux Pinus 5.16.19-200.fc35.x86_64 1 SMP PREEMPT Fri Apr 8 15:34:44 UTC 2022 x86_64
Database Type  | mysql
Database Version  | 10.5.13-MariaDB
Database Collation  | utf8mb4_general_ci
Database Connection Collation | utf8mb4_general_ci
Database Connection Encryption  | None
Database Server Supports Connection Encryption  | No
PHP Version | 8.0.17
Web Server | nginx/1.20.2
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
User Agent | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0

**Comment by astridx** [comment]
Thank you for explaining it so clearly. I made a mess of things. I hadn't thought of the component at all. It is actually no longer necessary in the Joomla 4 version. But I didn't dare to delete it completely yet. I have only corrected the error. Thank you very much again. The error should no longer occur in version 4.0.5.

**Comment by bubi-luka** [comment]
4.0.5 works great. All the errors I got before are now gone. And the option to display elevation profile outside the map is wonderful! Thank you
