### ISSUE TITLE
table of Additional Information of the GPX File

### ISSUE THREAD

**Issue by camminateinfriuli** [astridx/pkg_aggpxtrack#28]
Aggpxtrack is really cool, I saw in a post Anleitung Joomla 3 # 17
If your GPX file contains more information, you can display this imformation below the map. In Custom Field options, select which information to display. You can choose

Distance,
Name of the track,
Start time,
Moving time,
Total time,
Moving pace,
Moving speed,
Total speed,
Elevation (min),
Elevation (max),
Elevation (gain),
Elevation (loss),
Average heart rate and
Average temperature.
The entry appears in the frontend below the map. Each entry has a CSS ID and can be created in the custom.css - or user.css - of your template.

The table is very beautiful I only have a problem the TR lines are too high inspecting with Chrome I see a padding set to 1.

how can I bring the padding to 0 or make sure that the table does not have such high rows?

what should I put in the custom.css or user.css?

[https://camminateinfriuli.it/m-itinerari/m-itinerari-all/761-anello-monti-cereis-e-chiarandeit-da-borgo-del-bianco-2.html](url)

**Comment by astridx** [comment]
CSS depends on the template.  Can you give me a link to the website where you want to show the track?

**Comment by astridx** [comment]
@camminateinfriuli 
I can't find any article on the site https://camminateinfriuli.it/ that has aggpxtrack included. Can you please provide the direct link?

**Comment by camminateinfriuli** [comment]
sorry, the domain is new and the provider restored a backup to try to fix
the old plugin problem tomorrow restore the missing articles on the test
site so you can check.

Il lun 9 mag 2022, 21:04 Astrid ***@***.***> ha scritto:

**Comment by camminateinfriuli** [comment]
https://camminateinfriuli.it/joomla3/m-itinerari/m-itinerariud/761-anello-villa-santina-avaglio-lauco2.html

**Comment by camminateinfriuli** [comment]
For problems with the new provider I am redoing the site in J4, for my itineraries, as you can see in the old site in J3, I need to have a summary table (https://camminateinfriuli.altervista.org), I was using gpxtrackmap but it is no longer supported.

At the moment I managed to get the table using your aggpxtrack plugin which uses leaflet-gpx.

As seen here https://camminateinfriuli.it/test/index.php/provincia-di-pordenone/facili/villa-emma-da-arcola

the table is too high and does not solve my problem, I would like to extrapolate some data from the trace with the methods:
• get_distance (): returns the total track distance, in meters
• get_total_time (): returns the total track time, in milliseconds
• get_total_speed (): returns the average total speed in km per hour
• get_elevation_min (): returns the lowest elevation, in meters
• get_elevation_max (): returns the highest elevation, in meters
• get_elevation_gain (): returns the cumulative elevation gain, in meters
• get_elevation_loss (): returns the cumulative elevation loss, in meters

I found the explanation is logical and simple but without an example I just can't get out of it.

The thing I would need most is to save those values ​​in the joomla database in the table of additional fields created (distance, total time, speed, vertical drop, minimum altitude, maximum altitude, gain on ascent and gain on descent)

I had thought about modifying this code to update the values ​​in the database:

<?php
defined('_JEXEC') or die('Restricted Access');

use Joomla\CMS\Factory;

$db = Factory::getDbo();
     $session =& JFactory::getSession();
     $articleid = $session->get('articleid');


if ($articleid->id == 0)
{
	echo "Not article select";
}
else
{
	$email = $me->email; 
	// change the case of the email address
	$email_uppercase = strtoupper($email);
	if ($email == $email_uppercase)
	{
		$new_email = strtolower($email);
	}
	else
	{
		$new_email = $email_uppercase;
	}
	
	$query = $db->getQuery(true);

	$fields = array($db->quoteName('email') . " = '{$new_email}'");

	$conditions = array($db->quoteName('id') . ' = ' . $me->id); 

	$query->update($db->quoteName('#__users'))->set($fields)->where($conditions);

	echo $db->replacePrefix((string) $query);
	
	$db->setQuery($query);

	if ($result = $db->execute())
	{
		echo "Email case successfully changed!";
	}
}


I want to learn but it's not easy, the most difficult thing is the interaction between the code and the system.

Objectively I don't expect to enjoy her attention, I guess she has other things to think about, but I hope she can help me with her great experience, maybe it's child's play for her, a short pastime, for me it's a mission impossible.

**Comment by astridx** [comment]
> The thing I would need most is to save those values ​​in the joomla database in the table of additional fields created (distance, total time, speed, vertical drop, minimum altitude, maximum altitude, gain on ascent and gain on descent)

Unfortunately, aggpxtrack does not do that. The main purpose of the extension is the display on a map. The values you mention are calculated and displayed at the same time the GPX file is opened, if the display is enabled in the options.

**Comment by camminateinfriuli** [comment]
> Unfortunately, aggpxtrack does not save those values ​​in the joomla database. The main purpose of the extension is the display on a map. The values you mention are calculated and displayed at the same time the GPX file is opened, if the display is enabled in the options.


I know, at least you can solve the problem of too high table rows?
