### ISSUE TITLE
4.0.5: bug when uploading gpxtrack

### ISSUE THREAD

**Issue by jojo12** [astridx/pkg_aggpxtrack#29]
when I try to create a new agosm and want to upload a gpxtrack, I get an error notification:
"Dateityp nicht unterstützt".
Further in the visible window of mediamanager, the folder com_aggpxtrack is visible, but the gpx files inside are not shown!
In the common mediamanager I see these files.
I inserted in the options the gpx...

**Comment by astridx** [comment]
Did you see this: https://github.com/astridx/pkg_aggpxtrack/issues/18
