### ISSUE TITLE
After update Joomla 4.2.3 : Cannot save with selected GPX file

### ISSUE THREAD

**Issue by ebbomuc** [astridx/pkg_aggpxtrack#30]
After updating to Joomla 4.2.3 I am not able to save the article after selecting a file. Get the message "This value is not valid".
Just noticed that link will be saved and map will be shown, see attached screenshot. If this is wrong place to mention this, please close / delete issue.
![Bildschirmfoto 2022-09-28 um 17 17 12](https://user-images.githubusercontent.com/31387386/192821553-7cbd1ca7-b88d-4f37-8bef-b8433705173f.jpg)

**Comment by camminateinfriuli** [comment]
I tried the solution at the link of the forum in German but while creating queglio override it does not work for me, also because I do not use the cassiopea template and those js files are not in the positions indicated by the solution. Unfortunately this problem makes it very difficult to use the plugin.

**Comment by ebbomuc** [comment]
Maybe this helps you (german language), it works with my site
https://forum.joomla.de/thread/16791-joomla-4-2-3-und-aggpxtracks-problem-beim-speichern-des-verlinkten-data-filea/

**Comment by camminateinfriuli** [comment]
I tried that solution, maybe I'm too incompetent, the folders where to copy the two js files didn't exist, I created them, I copied the two js files and modified them as per instructions, but it didn't work. Maybe I did something wrong or the instructions are made for very experienced people.

**Comment by camminateinfriuli** [comment]
Ich habe diese Lösung ausprobiert, vielleicht bin ich zu inkompetent, die Ordner, in die die beiden js-Dateien kopiert werden sollen, existierten nicht, ich habe sie erstellt, ich habe die beiden js-Dateien kopiert und gemäß den Anweisungen geändert, aber es hat nicht funktioniert. Vielleicht habe ich etwas falsch gemacht oder die Anleitung ist für sehr erfahrene Leute gemacht.

**Comment by astridx** [comment]
@camminateinfriuli What does " but it didn't work." mean exacly?

**Comment by astridx** [comment]
There is now a working version of aggpxtracks for the latest Joomla version. Unfortunately, you can no longer select the GPX file in the custom field, but have to enter the correct path yourself. 



Here are some explanatory pictures: https://github.com/astridx/pkg_aggpxtrack/issues/18

Here is the version for download: https://github.com/astridx/pkg_aggpxtrack/releases/tag/v5.0.0

**Comment by hvdmeer** [comment]
Hi Astrid. I know this issue is closed but is it foreseeable the selecting a GPX would again be possible in a future 4.x version or does it just not work that way anymore?
(I'm looking into upgrading my site to J4 where I use your plugin)

**Comment by astridx** [comment]
I do not know this for sure at the moment. It depends on how the media field develops. I had built on this one.

Please note that there is no update for j4 of this extension. the old version must be uninstalled and the new one installed. I have not yet managed to automate this. See https://github.com/astridx/pkg_aggpxtrack/blob/master/README.md

**Comment by astridx** [comment]
In Joomla 4.2.5 the file is again selectable via media field when updating to this version https://github.com/astridx/pkg...track/releases/tag/v5.0.1.
