### ISSUE TITLE
No route displayed for some gpx files on my page

### ISSUE THREAD

**Issue by FrankReisenhofer** [astridx/pkg_aggpxtrack#45]
Hello all together,

On my webside some routes are shown correctly and for some nothing is shown.

Working example:
https://www.reisenhofer.de/index.php/de/fotos-de?view=article&id=461:hier-waren-wir-unterwegs-17&catid=42:albanien-2023

Not working example: https://www.reisenhofer.de/index.php/de/fotos-de?view=article&id=439:hier-waren-wir-unterwegs-16&catid=41:griechenland2022

Any idea what might cause this? Maybe a cashing issue?

**Comment by chrisssi2** [comment]
What are your settings for `Access-Control-Allow-Origin`. See the message in the console at the bottom right on the image.
![x](https://github.com/astridx/pkg_aggpxtrack/assets/124769469/75594662-4a42-46bc-b8ac-7e1c06745d44)

**Comment by astridx** [comment]
What are your settings for `Access-Control-Allow-Origin`. See the message in the console at the bottom right on the image.
![x](https://github.com/astridx/pkg_aggpxtrack/assets/124769469/75594662-4a42-46bc-b8ac-7e1c06745d44)

**Comment by FrankReisenhofer** [comment]
@astridx : Thanks for your hint. I am not so familiar with debugging webpages..So I did not check the console output in the browser.

I adjusted the .htaccess file like described e.g. https://subscription.packtpub.com/book/web-development/9781784393779/4/ch04lvl1sec28/cors-in-joomla.

Looks like this is solving the issue. No clue why this was suddently necessary :-(.

Thanks for your help.
