### ISSUE TITLE
Solved: More maps on article

### ISSUE THREAD

**Issue by Andysh1** [astridx/pkg_aggpxtrack#8]
Hi Astrid, thanks for your work!
I'd like to ask you if is possible to show more than one map on the same articles or not. 
Bye
Andrea

**Comment by astridx** [comment]
Hi Andrea,
what do you mean exactly? Do you want to show more than one track? In this case you have to create on custom field for every track?
Does this answer your question?

**Comment by Andysh1** [comment]
Sorry Astrid, I realized that I explained my self very bad.
In joomla, I want to show on an article two maps, every maps has one track on it. I did it, but a saw only one map (the first one). The other show a blank space with the download button.
To do that I made two fields in the field section, then in the article I link the first field with the first track and the second field with the second track. On the article I use {field1} to show the first and {field2} to show the second, but, the second show only the download button.
Is it possible or I’m doing something wrong?
Andrea

**Comment by astridx** [comment]
Dear Andrea, I just tried it with the [latest version](https://github.com/astridx/pkg_aggpxtrack/releases/download/v1.1.6/pkg-aggpxtrack-1.1.6.zip). It works for me. I could see two track with map in one article.  I have tested with Protostar and a Helix 3 template.

Which template do you use? If it is not Protstar, could you please test it with Protostar? 

Is it possible to view the page online?

**Comment by Andysh1** [comment]
Good evening Astrid,
I think the problem is when you set to "on" the  option  "Show map selection". In this case there is an error loading the layer, so it loads the first map, exit with error and does not load the second track. I tasted it on my template (gantry5) and protostar too.
Have a nice evening

**Comment by astridx** [comment]
Thank you for your hint. There was indeed a problem. Version 1.1.7 should solve this. This (Version 1.1.7 of ag_gpxtrack) should be installable via the joomla updater.

Does it actually solve your problem?

**Comment by Andysh1** [comment]
Good afternoon Astrid,
I installed the update and now it show correctly two tracks, but, unfortunately there is always a but with software, it does not show the track points icons (it show only icons of start and end points ).
Thank you and have a nice evening
Andrea

**Comment by astridx** [comment]
Dear Andrea,
You mean the waypoints in the GPX file, right? Not the kilometer points.

I just tested one of my example files with a default icon and a custom icon for the GPX waypoints. In both of them the waypoints are displayed. 
Could you please try this once in your installation? You can find the example file under` images/com_aggpxtrack/la-gabarra-vereda-de-la-costa-vereda-de-la-marchenilla-28-oc.gpx`

Are they displayed in your installation?

![gpxtrack](https://user-images.githubusercontent.com/9974686/109426108-0fd82b80-79ec-11eb-8c88-25e7fdaebb37.PNG)

**Comment by Andysh1** [comment]
Good morning Astrid,
Yes, I mean the waypoints in the GPX file. 
Your track is showed correctly on my page, so I checked the gpx data. I notice that my waypoints  have more information of yours.
This is a waypoint of your track:
<wpt lat="36.067340" lon="-5.490432">
    <ele>170.8</ele>
    <time>2017-10-28T14:11:54Z</time>
    <name>ABREVADERO</name>
    <cmt>ABREVADERO</cmt>
    <desc>ABREVADERO</desc>
  </wpt>
This is mine (Garmin GPS Map 64st)
 <wpt lon="13.81812600" lat="44.94092700">
  <ele>57</ele>
  <time>2021-02-27T14:49:11.000Z</time>
  <name>01</name>
  <cmt>Kazun</cmt>
  <desc>&lt;div>
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Vecchio Kazun&lt;/p>&lt;/div></desc>
  <sym>Default</sym>
  <extensions>
   <ql:key>392cc001e1cd7a8f27da080729e5f9cf</ql:key>
   <ql:flags>6</ql:flags>
   <ql:bubble width="300" xoff="-320" yoff="-150"/>
   <ql:history>
    <ql:event>
     <ql:icon>://icons/48x48/Start.png</ql:icon>
     <ql:time>2021-02-28T09:12:23.481Z</ql:time>
     <ql:comment>Initial version.</ql:comment>
    </ql:event>
    <ql:event>
     <ql:icon>://icons/waypoints/32x32/Default.png</ql:icon>
     <ql:time>2021-03-01T09:29:02.551Z</ql:time>
     <ql:comment>Changed icon</ql:comment>
    </ql:event>
    <ql:event>
     <ql:icon>://icons/48x48/EditText.png</ql:icon>
     <ql:time>2021-03-01T09:29:15.170Z</ql:time>
     <ql:comment>Changed description</ql:comment>
    </ql:event>
   </ql:history>
   <wptx1:WaypointExtension/>
  </extensions>
 </wpt>
If I clean my waypoint of all information after <desc> and it works correctly. In the old version of your component my waypoint with all its informations worked correctly too.
I hope this helps
Have a nice week
Andrea

**Comment by Andysh1** [comment]
Good morning Astrid,
Yes, I mean waypoint in gpx file. I tried your track and it works. I notice that my waypoint has more information respect yours.
I attached my test trace... I hope it can helps.
I cleaned my waypoint of all information not present on your track and now it works correctly. In the previous version of your component my trackpoints worked correctly too.
Have a nice week
Andrea
[Test.zip](https://github.com/astridx/pkg_aggpxtrack/files/6060709/Test.zip)


e week and thank you

**Comment by agi-code** [comment]
Dear Andrea.
It works for me with your file. Maybe there is a misunderstanding. I have not included this in the Read.me up to know. 

In your GPX file the waypoint has a symbol tag like this `<sym>Default</sym>`.. 

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx xmlns:wptx1="http://www.garmin.com/xmlschemas/WaypointExtension/v1" xmlns:gpxdata="http://www.cluetrust.com/XML/GPXDATA/1/0" xmlns="http://www.topografix.com/GPX/1/1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd http://www.garmin.com/xmlschemas/WaypointExtension/v1 http://www.garmin.com/xmlschemas/WaypointExtensionv1.xsd http://www.qlandkarte.org/xmlschemas/v1.1 http://www.qlandkarte.org/xmlschemas/v1.1/ql-extensions.xsd http://www.cluetrust.com/XML/GPXDATA/1/0 http://www.cluetrust.com/Schemas/gpxdata10.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" creator="QMapShack 1.15.2 http://www.qlandkarte.org/" xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" xmlns:rmc="urn:net:trekbuddy:1.0:nmea:rmc" xmlns:tp1="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" version="1.1" xmlns:ql="http://www.qlandkarte.org/xmlschemas/v1.1">
 <metadata>
  <name>Test</name>
  <time>2021-02-28T09:14:14.059Z</time>
 </metadata>
 <wpt lon="13.81812600" lat="44.94092700">
  <ele>57</ele>
  <time>2021-02-27T14:49:11.000Z</time>
  <name>01</name>
  <cmt>KASUN</cmt>
  <desc>&lt;div>
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Vecchio KAzun&lt;/p>&lt;/div></desc>

  <sym>Default</sym>

  <extensions>
   <ql:key>392cc001e1cd7a8f27da080729e5f9cf</ql:key>
   <ql:flags>6</ql:flags>
   <ql:bubble width="300" xoff="-320" yoff="-150"/>`
...
```


If this is so, then an icon must be created for the waypoint in the options of the custom field. This is because some users have different types of waypoints (viewpoint, restaurant ...) and like to show them with different icons. 

Your can create the icon for your waypoint like this:

![wpt](https://user-images.githubusercontent.com/73401898/109538821-d0c7da00-7ac0-11eb-8863-b3e0bb2737d9.PNG)

If you don't like a special icon, you have to delete the symbol tag in the GPX file.

**Comment by astridx** [comment]
Dear Andrea.
It works for me with your file. Maybe there is a misunderstanding. I have not included this in the Read.me up to know. 

In your GPX file the waypoint has a symbol tag like this `<sym>Default</sym>`.. 

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx xmlns:wptx1="http://www.garmin.com/xmlschemas/WaypointExtension/v1" xmlns:gpxdata="http://www.cluetrust.com/XML/GPXDATA/1/0" xmlns="http://www.topografix.com/GPX/1/1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd http://www.garmin.com/xmlschemas/WaypointExtension/v1 http://www.garmin.com/xmlschemas/WaypointExtensionv1.xsd http://www.qlandkarte.org/xmlschemas/v1.1 http://www.qlandkarte.org/xmlschemas/v1.1/ql-extensions.xsd http://www.cluetrust.com/XML/GPXDATA/1/0 http://www.cluetrust.com/Schemas/gpxdata10.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" creator="QMapShack 1.15.2 http://www.qlandkarte.org/" xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" xmlns:rmc="urn:net:trekbuddy:1.0:nmea:rmc" xmlns:tp1="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" version="1.1" xmlns:ql="http://www.qlandkarte.org/xmlschemas/v1.1">
 <metadata>
  <name>Test</name>
  <time>2021-02-28T09:14:14.059Z</time>
 </metadata>
 <wpt lon="13.81812600" lat="44.94092700">
  <ele>57</ele>
  <time>2021-02-27T14:49:11.000Z</time>
  <name>01</name>
  <cmt>KASUN</cmt>
  <desc>&lt;div>
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Vecchio KAzun&lt;/p>&lt;/div></desc>

  <sym>Default</sym>

  <extensions>
   <ql:key>392cc001e1cd7a8f27da080729e5f9cf</ql:key>
   <ql:flags>6</ql:flags>
   <ql:bubble width="300" xoff="-320" yoff="-150"/>`
...
```


If this is so, then an icon must be created for the waypoint in the options of the custom field. This is because some users have different types of waypoints (viewpoint, restaurant ...) and like to show them with different icons. 

Your can create the icon for your waypoint like this:

![wpt](https://user-images.githubusercontent.com/73401898/109538821-d0c7da00-7ac0-11eb-8863-b3e0bb2737d9.PNG)

If you don't like a special icon, you have to delete the symbol tag in the GPX file.

**Comment by Andysh1** [comment]
Good afternoon Astrid,
yes I am sure. With the old version my markers are showed well without I set "Different Custom Marker Layout".
With the new version, setting my own Icon and using as symbol tag "Default" everything works well.
Thank you
Andrea

**Comment by astridx** [comment]
Hi Andrea. 
Thank you for your feedback.
I can't say right now why it worked before with sym tag and without setting the icon. 
As it is now, it's ok for you, right? 
Can I close the issue?

**Comment by Andysh1** [comment]
Hi Astrid,
If you need some information about why it works without setting the icon, do not hesitate to ask me what you need.
Yes, I confirm that for me it is ok.
Andrea
