### ISSUE TITLE
Veld aan maken

### ISSUE THREAD

**Issue by Peter-59** [astridx/pkg_aggpxtrack#9]
Het lukt mij niet om een veld in Joomla aan te maken als type gps xtrack.
Ik heb de extensie gedownload versie 1.1.7 en via de installer geinstalleerd. Bij plugins is deze niet te vinden maar via beheer extensies zie ik hem wel. Ook is deze ingeschakeld. Mediainstellingen heb ik toegevoegd zoals omschreven.
Toch kan ik bij veld aanmaken het type van de extensie niet vinden in het rolmenu bij veld aanmaken.

Wie kan mij op weg helpen

**Comment by sonnemondundsterne** [comment]
--
Dutch 

Ik moet het vragen, zie je afbeelding 1 niet, ook al heb je de plug-in geactiveerd?

Welke Joomla-versie gebruikt u? 

--

English

I have to ask, you do not see picture 1 even though you have activated the plugin?

Which Joomla version are you using? 

--

German

Ich muss nachfragen, du siehst Bild 1 nicht, obwohl du das Plugin aktiviert hast?

Welche Joomla Version nutzt du?

--

1 

![Custom Field](https://user-images.githubusercontent.com/9974686/51280068-02fc4780-19df-11e9-8cfc-9b864ac974e2.png)


2

![ActivatePlugin](https://user-images.githubusercontent.com/9974686/51280066-0263b100-19df-11e9-8113-647e1429ae3d.png)

**Comment by astridx** [comment]
--
Dutch 

Ik moet het vragen, zie je afbeelding 1 niet, ook al heb je de plug-in geactiveerd?

Welke Joomla-versie gebruikt u? 

--

English

I have to ask, you do not see picture 1 even though you have activated the plugin?

Which Joomla version are you using? 

--

German

Ich muss nachfragen, du siehst Bild 1 nicht, obwohl du das Plugin aktiviert hast?

Welche Joomla Version nutzt du?

--

1 

![Custom Field](https://user-images.githubusercontent.com/9974686/51280068-02fc4780-19df-11e9-8cfc-9b864ac974e2.png)


2

![ActivatePlugin](https://user-images.githubusercontent.com/9974686/51280066-0263b100-19df-11e9-8113-647e1429ae3d.png)

**Comment by Peter-59** [comment]
Afbeelding 1 zie ik wel. Maar zie niet de optie AGGPtrack optie.
Als ik bij de plugins kijk zie ik aggptrack niet maar als ik met beheer extensies ga zoeken zie ik aggptrack wel en heeft deze ook een groen vinkje.

Ik gebruik joomla versie 3.9.25

**Comment by astridx** [comment]
Ik ben bang dat ik me daar niet mee kan identificeren. Ik heb net opnieuw geïnstalleerd en bij mij is er geen fout. Kan het een conflict zijn met een andere extensie?

--

--

Unfortunately, I cannot reproduce  this. I have just reinstalled and there is no error for me. Could it be a conflict with another extension?

--


Ich kann das leider nicht nachvollziehen. Ich habe gerade neu installiert und bei mir gibt es keinen Fehler. Kann es ein Konflikt mit einer anderen Erweiterung sein?


![Plugins-test-Administration](https://user-images.githubusercontent.com/9974686/114267874-94ac6100-99fe-11eb-8b89-1c0e74408394.png)

**Comment by Peter-59** [comment]
Inmiddels op een andere joomla website geinstalleerd. Geen probleem. Ik zal dus moeten gaan zoeken of er een extensie is die dit probleem veroorzaakt.  Dat wordt een puzzel.

**Comment by astridx** [comment]
Bedankt voor de feedback. Misschien is er iets misgegaan met de installatie een herinstallatie over de huidige installatie helpt? In ieder geval zou ik feedback op prijs stellen. Misschien is er een algemeen probleem met een andere extensie dat ik kan oplossen als ik ervan weet.

--

Thanks for the feedback. Maybe something went wrong during the installation - a new installation over the current installation will help? In any case, I would be pleased to receive feedback. Maybe there is a general problem with another extension that I can solve if I know about it.

--


Danke für die Rückmeldung. Vielleicht ist bei der Installation etwas schief gelaufen eine erneute Installation über die aktuelle Installation hilft? In jedem Fall würde ich mich über eine Rückmeldung freuen. Vielleicht ist ja ein generelles Problem mit einer anderen Erweiterung, das ich lösen kann, wenn ich davon weiß.

**Comment by astridx** [comment]
Ben je erachter gekomen wat het probleem was? Is het probleem nu opgelost?

--

Did you find out what the problem was? Is the problem solved now?
